services:
  nginx:
    image: ernestofernandezdev/proxy:{commit-code}
    ports:
      - "80:80"
    depends_on:
      - spring-app  # Asegúrate de que spring-app esté disponible

  spring-app:
    image: ernestofernandezdev/api:{commit-code}
    ports:
      - "8080:8080"