name: Build and Deploy Docker Image to Docker Hub

on:
  push:
    branches:
      - master

jobs:

  build-spring-img:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'

    - name: Build the package
      run: mvn -f ./portfolio-api/pom.xml clean package

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/portfolio-api/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ vars.SPRING_IMG_NAME }}:${{ github.sha }} ./portfolio-api

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ vars.SPRING_IMG_NAME }}:${{ github.sha }}

    - name: Logout from Docker Hub
      run: |
        docker logout



  build-nginx-img:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ vars.NGINX_IMG_NAME }}:${{ github.sha }} .

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ vars.NGINX_IMG_NAME }}:${{ github.sha }}

    - name: Logout from Docker Hub
      run: |
        docker logout

  restart-services:
    runs-on: ubuntu-latest
    needs: [build-spring-img, build-nginx-img]

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        name: portfolio-ssh-key
        known_hosts: ${{ secrets.SERVER_IP }}
    
    - name: SSH to remote server and restart Docker Compose
      run: |
        ssh -i ~/.ssh/portfolio-ssh-key root@${{ secrets.SERVER_IP }} echo "hello"

    - name: SSH to remote server and restart Docker Compose
      run: |
        ssh -i ~/.ssh/portfolio-ssh-key root@${{ secrets.SERVER_IP }} << EOF
          echo "Restarting Docker Compose service..."
          docker-compose down
          curl https://raw.githubusercontent.com/ernestofernandezdev/portfolio/refs/heads/master/docker-compose.yml > docker-compose
          sed -i 's/{commit-code}/${{github.sha}}/' docker-compose.yml
          docker rmi -f $(docker images -aq)
          docker-compose up -d
          echo "Docker Compose restarted successfully."
        EOF